nforcer_body_spam {
  type = "content";
  filter = "text";
  map = "https://raw.githubusercontent.com/nforceroh/rspamd_config/main/maps.d/body.spam.map";
  symbol = "nforcer_body_spam";
  description = "Spam body phrases and words";
  score = 3.0;
  one_shot = true;          # Only trigger once per email
  regexp = true;            # Required if map contains /regex/ patterns
}