multimap_whitelist_domain {
  type = "from";
  filter = "email:domain";
  map = "https://raw.githubusercontent.com/nforceroh/rspamd_config/main/maps.d/whitelist.domain.map";
  score = -50.0;
  symbol = "multimap_whitelist_domain";
  description = "Domain whitelist";
  regexp = true;
  one_shot = true;
  
    # REJECTION MATCHING:
    # Extortionists: Fail SPF, fail DKIM, is_local is false -> Map is skipped.
    # Alertmanager: is_local resolves true -> Map is safely evaluated.
  require_symbols = "R_SPF_ALLOW | R_DKIM_ALLOW | is_local";
}
