nforcer_asn_block {
  type = "asn";
  map = "https://raw.githubusercontent.com/nforceroh/rspamd_config/main/maps.d/asn.block.map";
  score = 2.5;
  symbol = "nforcer_asn_block";
  description = "Sender from a blacklisted ASN";
}
