nforcer_country_block {
  type = "country";
  map = "https://raw.githubusercontent.com/nforceroh/rspamd_config/main/maps.d/country.block.map";
  score = 1.5;
  symbol = "nforcer_country_block";
  description = "Country risk list";
  one_shot = true; # Ensures the symbol is added only once per message
}
