# Only applies to SPOOFED_UNAUTH emails
LOCAL_HOSTED_DOMAIN {
    type = "from";
    filter = "email:domain";
    map = "https://raw.githubusercontent.com/nforceroh/rspamd_config/main/maps.d/hosted.domains.map";
    score = 0.0; # We use a 0.0 score because this rule is strictly a tracking symbol
    symbol = "LOCAL_HOSTED_DOMAIN";
    description = "List of local domains hosted on this cluster";
}