multimap_whitelist_email {
  type = "from";
  filter = "email:addr";
  map = "https://raw.githubusercontent.com/nforceroh/rspamd_config/main/maps.d/whitelist.email.map";
  score = -50.0;
  symbol = "multimap_whitelist_email";
  description = "Email address whitelist";
  one_shot = true;
}
