multimap_whitelist_domain {
  type = "from";
  filter = "email:domain";
  map = "https://raw.githubusercontent.com/nforceroh/rspamd_config/main/maps.d/multimap.whitelist.domain.map";
  score = -50.0;
  symbol = "multimap_whitelist_domain";
  description = "Domain whitelist";
  regexp = true;
  one_shot = true;
}
