nforcer_language_block {
  type = "language";
  map = "https://raw.githubusercontent.com/nforceroh/rspamd_config/main/maps.d/multimap.language.block.map";
  score = 1.0;
  symbol = "nforcer_language_block";
  description = "Language risk list";
}
