nforcer_from_whitelist {
  type = "from";
  filter = "email:addr";
  map = "https://raw.githubusercontent.com/nforceroh/rspamd_config/main/maps.d/multimap.from.whitelist.map";
  score = -8.0;
  symbol = "nforcer_from_whitelist";
  description = "Sender/domain whitelist (Authenticated)";
}
