multimap_blacklist_domain {
  type = "from";
  filter = "email:domain";
  map = "https://raw.githubusercontent.com/nforceroh/rspamd_config/main/maps.d/multimap.blacklist.domain.map";
  score = 10.0;
  symbol = "multimap_blacklist_domain";
  description = "Domain blacklist";
  regexp = true;
  one_shot = true;
}
