nforcer_language_block {
  type = "selector";
  selector = "languages";
  map = "https://raw.githubusercontent.com/nforceroh/rspamd_config/main/maps.d/multimap.language.block.map";
  symbol = "nforcer_language_block";
  description = "Blocked languages detected in message";
  score = 1.0;
  one_shot = true;
}
