nforcer_header_php_spam {
  type = "header";
  map = "https://raw.githubusercontent.com/nforceroh/rspamd_config/main/maps.d/multimap.header.php.map";
  score = 3.0;
  symbol = "nforcer_header_php_spam";
  description = "Suspicious PHP-related header patterns";
}
