multimap_blacklist_email {
  type = "from";
  filter = "email:addr"; 
  map = "https://raw.githubusercontent.com/nforceroh/rspamd_config/main/maps.d/multimap.blacklist.email.map";
  score = 10.0;
  symbol = "multimap_blacklist_email";
  description = "Email address blacklist";
  one_shot = true;
}
